version: '3.8'

services:
    db:
      build:
        context: ../..
        dockerfile: docker/dockerfiles/postgres.dockerfile
      image: spycats/postgres:1.0.0
      env_file:
        - ../../.env.example
      container_name: spycats-db
      ports:
        - '5434:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - spycats-net

volumes:
  postgres_data:

networks:
  spycats-net:
    external: true
